import { Project, ProjectTag, ProjectType } from '@/types/project';

export const projects: Project[] = [
  {
    id: 'bob-le-developpeur-2024',
    title: 'bob-le-developpeur.title',
    description: 'bob-le-developpeur.description',
    date: '2024-06-30',
    type: ProjectType.WORK,
    favorite: false,
    images: {
      mobile: [
        '/projects/bob/bob-mobile-1.webP',
        '/projects/bob/bob-mobile-2.webP',
      ],
      desktop: [
        '/projects/bob/bob-desktop-1.webP',
        '/projects/bob/bob-desktop-2.webP',
        '/projects/bob/bob-desktop-3.webP',
        '/projects/bob/bob-desktop-4.webP',
        '/projects/bob/bob-desktop-5.webP',
        '/projects/bob/bob-desktop-6.webP',
        '/projects/bob/bob-desktop-7.webP',
      ],
      header: '/projects/bob/bob-desktop-1.webP',
    },
    tags: [
      ProjectTag.NEXTJS,
      ProjectTag.TYPESCRIPT,
      ProjectTag.TAILWIND,
      ProjectTag.NESTJS,
      ProjectTag.POSTGRESQL,
      ProjectTag.DOCKER,
      ProjectTag.PROG_WEB_APP,
      ProjectTag.REACT_NATIVE,
    ],
    slug: 'bob-le-developpeur',
    link: 'https://www.bob-le-developpeur.com/portfolio',
  },
  {
    id: '08347cc0-e16c-49d4-bd10-31ae7c341b52',
    title: 'sakana-san.title',
    description: 'sakana-san.description',
    date: '2024-04-10',
    type: ProjectType.FREELANCE,
    favorite: true,
    images: {
      mobile: [
        '/projects/sakana-san/sakana-san-mobile-1.webP',
        '/projects/sakana-san/sakana-san-mobile-2.webP',
        '/projects/sakana-san/sakana-san-mobile-3.webP',
        '/projects/sakana-san/sakana-san-mobile-4.webP',
        '/projects/sakana-san/sakana-san-mobile-5.webP',
        '/projects/sakana-san/sakana-san-mobile-6.webP',
        '/projects/sakana-san/sakana-san-mobile-7.webP',
        '/projects/sakana-san/sakana-san-mobile-8.webP',
      ],
      desktop: [
        '/projects/sakana-san/sakana-san-desktop-1.webP',
        '/projects/sakana-san/sakana-san-desktop-2.webP',
        '/projects/sakana-san/sakana-san-desktop-3.webP',
        '/projects/sakana-san/sakana-san-desktop-4.webP',
        '/projects/sakana-san/sakana-san-desktop-5.webP',
        '/projects/sakana-san/sakana-san-desktop-6.webP',
        '/projects/sakana-san/sakana-san-desktop-7.webP',
        '/projects/sakana-san/sakana-san-desktop-8.webP',
      ],
      header: '/projects/sakana-san/sakana-san-desktop-2.webP',
    },
    tags: [
      ProjectTag.NEXTJS,
      ProjectTag.TYPESCRIPT,
      ProjectTag.TAILWIND,
      ProjectTag.NESTJS,
      ProjectTag.POSTGRESQL,
      ProjectTag.DOCKER,
      ProjectTag.PROG_WEB_APP,
    ],
    slug: 'sakana-san',
    github: 'https://github.com/noep-sakana-san/sakana-san-web',
    link: 'https://sakana-san.noe-philippe.fr/',
    customerUrl: 'https://www.instagram.com/sakana__san_',
  },
  {
    id: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
    title: 'tildev.title',
    description: 'tildev.description',
    date: '2024-05-15',
    type: ProjectType.FREELANCE,
    favorite: true,
    images: {
      mobile: [
        '/projects/tildev/tildev-mobile-1.webP',
        '/projects/tildev/tildev-mobile-2.webP',
        '/projects/tildev/tildev-mobile-3.webP',
        '/projects/tildev/tildev-mobile-4.webP',
      ],
      desktop: [
        '/projects/tildev/tildev-desktop-1.webP',
        '/projects/tildev/tildev-desktop-2.webP',
        '/projects/tildev/tildev-desktop-3.webP',
        '/projects/tildev/tildev-desktop-4.webP',
      ],
      header: '/projects/tildev/tildev-desktop-1.webP',
    },
    tags: [ProjectTag.NEXTJS, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'tildev',
    link: 'https://tildev.fr/',
    customerUrl: 'https://tildev.fr/',
  },

  {
    id: '2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q',
    title: 'kerluskellik.title',
    description: 'kerluskellik.description',
    date: '2024-01-05',
    type: ProjectType.FREELANCE,
    favorite: true,
    images: {
      mobile: [
        '/projects/kerluskellik/kerluskellik-mobile-1.webP',
        '/projects/kerluskellik/kerluskellik-mobile-2.webP',
        '/projects/kerluskellik/kerluskellik-mobile-3.webP',
        '/projects/kerluskellik/kerluskellik-mobile-4.webP',
      ],
      desktop: [
        '/projects/kerluskellik/kerluskellik-desktop-1.webP',
        '/projects/kerluskellik/kerluskellik-desktop-2.webP',
        '/projects/kerluskellik/kerluskellik-desktop-3.webP',
        '/projects/kerluskellik/kerluskellik-desktop-4.webP',
        '/projects/kerluskellik/kerluskellik-desktop-5.webP',
      ],
      header: '/projects/kerluskellik/kerluskellik-desktop-1.webP',
    },
    tags: [ProjectTag.NEXTJS, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'kerluskellik',
    github: 'https://github.com/Noe-p/kerluskellik',
    link: 'https://www.kerluskellik.fr/',
    customerUrl: 'https://www.kerluskellik.fr/',
  },
  {
    id: '3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r',
    title: 'romane-faupin.title',
    description: 'romane-faupin.description',
    date: '2023-02-18',
    type: ProjectType.FREELANCE,
    favorite: false,
    images: {
      mobile: [
        '/projects/romane-faupin/romane-faupin-mobile-1.webP',
        '/projects/romane-faupin/romane-faupin-mobile-2.webP',
        '/projects/romane-faupin/romane-faupin-mobile-3.webP',
        '/projects/romane-faupin/romane-faupin-mobile-4.webP',
      ],
      desktop: [
        '/projects/romane-faupin/romane-faupin-desktop-1.webP',
        '/projects/romane-faupin/romane-faupin-desktop-2.webP',
        '/projects/romane-faupin/romane-faupin-desktop-3.webP',
      ],
      header: '/projects/romane-faupin/romane-faupin-desktop-1.webP',
    },
    tags: [ProjectTag.NEXTJS, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'romane-faupin',
    github: 'https://github.com/Noe-p/romane-faupin',
    link: 'https://www.romanefaupin.fr/',
    customerUrl: 'https://www.romanefaupin.fr/',
  },
  {
    id: '4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s',
    title: 'fast-foodie.title',
    description: 'fast-foodie.description',
    date: '2024-12-06',
    type: ProjectType.PERSONAL,
    favorite: true,
    images: {
      mobile: [
        '/projects/fast-foodie/fast-foodie-mobile-1.webP',
        '/projects/fast-foodie/fast-foodie-mobile-2.webP',
        '/projects/fast-foodie/fast-foodie-mobile-3.webP',
        '/projects/fast-foodie/fast-foodie-mobile-4.webP',
        '/projects/fast-foodie/fast-foodie-mobile-5.webP',
      ],
      desktop: [],
      header: '/projects/fast-foodie/fast-foodie-mobile-1.webP',
    },
    tags: [
      ProjectTag.NEXTJS,
      ProjectTag.TYPESCRIPT,
      ProjectTag.TAILWIND,
      ProjectTag.POSTGRESQL,
      ProjectTag.PROG_WEB_APP,
      ProjectTag.NESTJS,
      ProjectTag.DOCKER,
    ],
    slug: 'fast-foodie',
    github: 'https://github.com/Noe-p/fast-foodie',
    link: 'https://fast-foodie.noe-philippe.fr/',
  },
  {
    id: '5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t',
    title: 'iggy.title',
    description: 'iggy.description',
    date: '2023-10-27',
    type: ProjectType.SCHOOL,
    favorite: true,
    images: {
      mobile: [
        '/projects/iggy/iggy-mobile-1.webP',
        '/projects/iggy/iggy-mobile-2.webP',
        '/projects/iggy/iggy-mobile-3.webP',
        '/projects/iggy/iggy-mobile-4.webP',
        '/projects/iggy/iggy-mobile-5.webP',
      ],
      desktop: [
        '/projects/iggy/iggy-desktop-1.webP',
        '/projects/iggy/iggy-desktop-2.webP',
        '/projects/iggy/iggy-desktop-3.webP',
      ],
      header: '/projects/iggy/iggy-desktop-1.webP',
    },
    tags: [
      ProjectTag.REACT_NATIVE,
      ProjectTag.TYPESCRIPT,
      ProjectTag.NEXTJS,
      ProjectTag.NESTJS,
      ProjectTag.DOCKER,
    ],
    slug: 'iggy',
    github: 'https://github.com/orgs/noep-iggy/repositories',
    link: 'https://iggy-landing-six.vercel.app/',
  },
  {
    id: '6f7g8h9i-0j1k-2l3m-4n5o-6p7q8r9s0t1u',
    title: 'perdus-en-foret.title',
    description: 'perdus-en-foret.description',
    date: '2022-06-16',
    type: ProjectType.SCHOOL,
    favorite: false,
    images: {
      mobile: [
        '/projects/perdus-en-foret/perdus-en-foret-mobile-1.webP',
        '/projects/perdus-en-foret/perdus-en-foret-mobile-2.webP',
        '/projects/perdus-en-foret/perdus-en-foret-mobile-3.webP',
        '/projects/perdus-en-foret/perdus-en-foret-mobile-4.webP',
        '/projects/perdus-en-foret/perdus-en-foret-mobile-5.webP',
        '/projects/perdus-en-foret/perdus-en-foret-mobile-6.webP',
      ],
      desktop: [],
      header: '/projects/perdus-en-foret/perdus-en-foret-mobile-1.webP',
    },
    tags: [ProjectTag.REACT_NATIVE, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'perdus-en-foret',
    github: 'https://github.com/VineBast/perdus-en-foret',
  },
];
